(* 
    This file is a part of IsarMathLib - 
    a library of formalized mathematics written for Isabelle/Isar.

    Copyright (C) 2026 Slawomir Kolodynski

    This program is free software; Redistribution and use in source and binary forms, 
    with or without modification, are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimer in the documentation and/or 
   other materials provided with the distribution.
   3. The name of the author may not be used to endorse or promote products 
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. *)

section \<open>Metrization of uniform spaces\<close>

theory MetricUniform_ZF_1 imports MetricUniform_ZF Real_ZF_2

begin

text\<open>This theory continues \<open>MetricUniform_ZF\<close> specializing to the 
  real valued pseudometrics. The ultimate goal is to show that every uniformity 
  is the supremum of a collection of uniformities generated by a pseudometric. In this
  theory we show the AC-free fragments of the proof of this fact.\<close>

subsection\<open>Defining pseudometrics with weighted chains\<close>

text\<open>This section describes a method of defining real valued pseudometrics through infimum 
  of the set of weights of all chains connecting two points. 
  The notions of chains and links is defined in the \<open>FiniteSeq_ZF\<close> theory, with some 
  properties proven in the \<open>Monoid_ZF_1\<close> theory.\<close>

text\<open>Since we will be using the set of non-zero natural numbers quite a lot, let's
  denote it $\mathbb{N}_1$\<close>

abbreviation positive_nat ("\<nat>\<^sub>1") where "\<nat>\<^sub>1 \<equiv> nat\<setminus>{0}"

text\<open>In the \<open>monoid1\<close> context we have defined a notion of \<open>ChainWeight\<close>.
  The next definition brings that notion into the \<open>reals\<close> context\<close>

definition (in reals) RChainWeight where
  "RChainWeight(w,c) \<equiv> monoid1.ChainWeight(\<real>,Add,w,c)"

text\<open>Given a chain of elements of $X$ and a weight function 
  $w:X\times X\rightarrow \mathbb{R}$ the weight of a chain is a real number.\<close>

lemma (in reals) chain_weight_real: 
  assumes "n\<in>nat" "c\<in>Chains(X,n,x,y)" "w:X\<times>X\<rightarrow>\<real>"
  shows "RChainWeight(w,c) \<in> \<real>"
  using assms add_group.monoid.chain_weight_type unfolding RChainWeight_def 
  by simp

text\<open>Given a weight function $w:X\rightarrow \mathbb{R}^+$ we define 
  the chain distance between two points $x,y\in X$ as the infimum of set of weights of
  all chains of nonzero length connecting $x$ and $y$.\<close>

definition (in reals) ChainDist where
  "ChainDist(X,w,x,y) \<equiv> inf({RChainWeight(w,c). c\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,y))})"

text\<open>If the weight function is valued in nonnegative real numbers then the weight of every chain
  in nonnegative.\<close>

lemma (in reals) chain_weight_nonneg: 
  assumes "n\<in>nat" "c\<in>Chains(X,n,x,y)" "w:X\<times>X\<rightarrow>\<real>\<^sup>+"
  shows "RChainWeight(w,c) \<in> \<real>\<^sup>+"
proof -
  from assms have "w O ChainLinks(c) : n\<rightarrow>\<real>\<^sup>+"
    using chain_links_fun(2) comp_fun by blast 
  with assms(1) have "(\<Sum>(w O ChainLinks(c))) \<in> \<real>\<^sup>+"
    using loop1_valid_in_group3 loop1.sum_nonneg_nonneg by simp
  then show "RChainWeight(w,c) \<in> \<real>\<^sup>+"
    using add_group.monoid1_valid_in_group monoid1.ChainWeight_def
    unfolding RChainWeight_def by simp
qed

text\<open>The \<open>chain_concat_weight1\<close> lemma from the \<open>monoid1\<close> context 
  rewritten using notation used in the \<open>reals\<close> context.\<close>

lemma (in reals) rchain_concat_weight:
  assumes "w:X\<times>X\<rightarrow>\<real>" "\<forall>x\<in>X. w`\<langle>x,x\<rangle> = \<zero>" "c\<^sub>1\<in>Chains(X,n\<^sub>1,x,y)" "c\<^sub>2\<in>Chains(X,n\<^sub>2,y,z)" and
    "n\<^sub>1\<in>nat" "n\<^sub>2\<in>nat"  
  shows "RChainWeight(w,Concat(c\<^sub>1,c\<^sub>2)) = RChainWeight(w,c\<^sub>1)\<ra>RChainWeight(w,c\<^sub>2)"
  using assms add_group.monoid1_valid_in_group monoid1.chain_concat_weight1
    unfolding RChainWeight_def by simp

text\<open>If the weight function is nonnegative and zero on the diagonal then the chain distance 
  obeys the triangle inequalitty\<close>

lemma (in reals) chain_dist_tr_ineq: 
  assumes "x\<in>X" "y\<in>X" "z\<in>X" and "w:X\<times>X\<rightarrow>\<real>\<^sup>+" "\<forall>x\<in>X. w`\<langle>x,x\<rangle> = \<zero>"
  shows "ChainDist(X,w,x,z) \<lsq> ChainDist(X,w,x,y) \<ra> ChainDist(X,w,y,z)"
proof -
  let ?W\<^sub>1 = "{RChainWeight(w,c). c\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,y))}"
  let ?W\<^sub>2 = "{RChainWeight(w,c). c\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,y,z))}"
  let ?W\<^sub>3 = "{RChainWeight(w,c). c\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,z))}"
  let ?W\<^sub>4 = "{w\<^sub>1\<ra>w\<^sub>2. \<langle>w\<^sub>1,w\<^sub>2\<rangle> \<in> ?W\<^sub>1\<times>?W\<^sub>2}"
  from R_are_reals assms(1,2,3,4) 
    have "?W\<^sub>1\<noteq>\<emptyset>" "?W\<^sub>2\<noteq>\<emptyset>" "?W\<^sub>3\<noteq>\<emptyset>" "?W\<^sub>4\<noteq>\<emptyset>" "antisym(ROrd)" "w:X\<times>X\<rightarrow>\<real>"
    using chains_nempty(4) cart_prod_nempty OrderedGroup_ZF_1_L4E func1_1_L1B 
    unfolding IsAmodelOfReals_def IsAnOrdField_def IsAnOrdRing_def IsLinOrder_def
      by auto
  have "?W\<^sub>4 \<subseteq> ?W\<^sub>3"
  proof
    fix v assume "v \<in> {w\<^sub>1\<ra>w\<^sub>2. \<langle>w\<^sub>1,w\<^sub>2\<rangle> \<in> ?W\<^sub>1\<times>?W\<^sub>2}"
    then obtain w\<^sub>1 w\<^sub>2 where "w\<^sub>1\<in>?W\<^sub>1" "w\<^sub>2\<in>?W\<^sub>2" and "v = w\<^sub>1\<ra>w\<^sub>2"
      by auto
    from \<open>w\<^sub>1\<in>?W\<^sub>1\<close> \<open>w\<^sub>2\<in>?W\<^sub>2\<close> obtain c\<^sub>1 c\<^sub>2 where 
      I: "w\<^sub>1 = RChainWeight(w,c\<^sub>1)"  "w\<^sub>2 = RChainWeight(w,c\<^sub>2)" and 
      II: "c\<^sub>1\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,y))" "c\<^sub>2\<in>(\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,y,z))"
      by auto
    let ?c\<^sub>3 = "Concat(c\<^sub>1,c\<^sub>2)"
    have "?c\<^sub>3 \<in> (\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,z))" and "RChainWeight(w,?c\<^sub>3) = v"
    proof -
      from II obtain n\<^sub>1 n\<^sub>2 where "n\<^sub>1\<in>\<nat>\<^sub>1" "n\<^sub>2\<in>\<nat>\<^sub>1" and
        III: "c\<^sub>1 \<in> Chains(X,n\<^sub>1,x,y)" "c\<^sub>2 \<in> Chains(X,n\<^sub>2,y,z)"
        by auto
      from assms(5) \<open>n\<^sub>1\<in>\<nat>\<^sub>1\<close> \<open>n\<^sub>2\<in>\<nat>\<^sub>1\<close> \<open>w:X\<times>X\<rightarrow>\<real>\<close> III 
      have "n\<^sub>1\<in>nat" "n\<^sub>2\<in>nat" "n\<^sub>1 #+ n\<^sub>2 #+ 1 \<in> \<nat>\<^sub>1" and
        "RChainWeight(w,?c\<^sub>3) = RChainWeight(w,c\<^sub>1)\<ra>RChainWeight(w,c\<^sub>2)"
        using rchain_concat_weight by auto
      with \<open>v = w\<^sub>1\<ra>w\<^sub>2\<close> I show "RChainWeight(w,?c\<^sub>3) = v" by simp
      from \<open>n\<^sub>1\<in>nat\<close> \<open>n\<^sub>2\<in>nat\<close> III \<open>n\<^sub>1 #+ n\<^sub>2 #+ 1 \<in> \<nat>\<^sub>1\<close>
      show "?c\<^sub>3 \<in> (\<Union>n\<in>\<nat>\<^sub>1. Chains(X,n,x,z))"
        using concat_chains(1) by force
    qed
    thus "v\<in>?W\<^sub>3" by auto
  qed
  from assms(4) \<open>?W\<^sub>4 \<subseteq> ?W\<^sub>3\<close> have "?W\<^sub>1\<subseteq>\<real>\<^sup>+" "?W\<^sub>2\<subseteq>\<real>\<^sup>+" "?W\<^sub>3\<subseteq>\<real>\<^sup>+" 
    using chain_weight_nonneg by auto
  from \<open>?W\<^sub>4\<subseteq>?W\<^sub>3\<close> \<open>?W\<^sub>3\<subseteq>\<real>\<^sup>+\<close> have "?W\<^sub>4\<subseteq>\<real>\<^sup>+" by blast
  from \<open>?W\<^sub>3\<noteq>\<emptyset>\<close> \<open>?W\<^sub>3\<subseteq>\<real>\<^sup>+\<close> \<open>?W\<^sub>4\<noteq>\<emptyset>\<close> \<open>?W\<^sub>4\<subseteq>\<real>\<^sup>+\<close> \<open>antisym(ROrd)\<close> \<open>?W\<^sub>4 \<subseteq> ?W\<^sub>3\<close>
  have "inf(?W\<^sub>3)\<lsq>inf(?W\<^sub>4)" 
    using nneg_has_nneg_inf(1) inf_incl_mono by simp
  with \<open>?W\<^sub>1\<noteq>\<emptyset>\<close> \<open>?W\<^sub>1\<subseteq>\<real>\<^sup>+\<close> \<open>?W\<^sub>2\<noteq>\<emptyset>\<close> \<open>?W\<^sub>2\<subseteq>\<real>\<^sup>+\<close> show ?thesis
    using nonneg_inf_sum_inf(2) unfolding ChainDist_def by simp
qed
  
subsection\<open>Metrization lemma\<close>

text\<open>The metrization theorem states that a uniform space is pseudometrizable if and only if 
  its uniformity has an countable base. In this sectiopn we show the key lemma that leads to 
  the metrization theorem.

  In the literature the metrization lemma (proven below) is usually stated as asserting
  existence of a pseudometric satisfying certain conditions. We prefer here a more explicit
  approach where we specify the construction of that pseudometric as a series of definitions,
  then show that the resulting function indeed satisfies the required conditions.
  The drawback of this approach is that we have to come up with names for the intermediate objects
  representing stages of that construction. Naming is hard, so as usual if the reader has an idea
  for better names please let me know. \<close>

text\<open>We define the \<open>DistWeight(\<U>,p)\<close> expression as equal to (real) $0$ if 
  $p\in\bigcap_{n\in\mathbb{N}} \mathcal{U}_n$ or otherwise equal to $(\frac{1}{2})^n$, where
  $n$ is the only natural number such that $p\in\mathcal{U}_n\setminus\mathcal{U}_{n+1}$.
  To understand the context in which this definition is intended to be used suppose 
  $\mathcal{U}:\mathbb{N}\rightarrow\mathcal{P}(X\times X)$ is a sequence of subsets 
  of $X\times X$ such that $\mathcal{U}_{n+1}\subseteq \mathcal{U}_n$ for $n\in\mathbb{N}$. 
  Then we have the identity 
  $\bigcup_{n\in \mathbb{N}} (\mathcal{U}_n\setminus\mathcal{U}_{n+1})=\mathcal{U}_0\setminus \bigcap_{n\in \mathbb{N}} \mathcal{U}_n$ 
  and for any $p\in\bigcup_{n\in \mathbb{N}} (\mathcal{U}_n\setminus \mathcal{U}_{n+1})$ 
  there is exactly one $n\in \mathbb{N}$ such that $p\in \mathcal{U}_n\setminus \mathcal{U}_{n+1}$
  This means that the set $\{n\in n\in \mathbb{N}: p\in \mathcal{U}_n\setminus \mathcal{U}_{n+1}\}$ 
  is a singleton and we can use the $\bigcup \{ x\} = x$ identity to extract its only element.\<close>

definition (in reals) DistWeight where 
  "DistWeight(\<U>,p) \<equiv> if p \<in> (\<Inter>n\<in>nat. \<U>`(n)) then \<zero> else pow(\<Union>{n\<in>nat. p\<in>(\<U>`(n)\<setminus>\<U>`(n #+ 1))},\<onehalf>)"

text\<open>Suppose $\mathcal{U}:\mathbb{N}\rightarrow \mathcal{P}(X\times X)$ is a sequence of subsets 
  of $X\times X$ such that $\mathcal{U}_{n+1}\subseteq \mathcal{U}_n$ 
  for all $n\in\mathbb{N}$.
  Assume further that $p\in\mathcal{U}_n\setminus \mathcal{U}_{n+1}$ for some $n\in\mathbb{N}$.
  Then \<open>DistWeight(\<U>,p)\<close> is equal to $\left(frac{1}{2}\right)^n$.\<close>

lemma (in reals) dist_weight_val: 
  assumes "\<U>:nat\<rightarrow>Pow(X\<times>X)" "\<forall>i\<in>nat. \<U>`(i #+ 1) \<subseteq> \<U>`(i)" and
    "n\<in>nat" "p \<in> (\<U>`(n)\<setminus>\<U>`(n #+ 1))" 
  shows "DistWeight(\<U>,p) = pow(n,\<onehalf>)"
proof -
  let ?\<V> = "{\<langle>i,\<U>`(i)\<setminus>\<U>`(i #+ 1)\<rangle>. i\<in>nat}"
  have I: "\<forall>i\<in>nat. ?\<V>`(i) = \<U>`(i)\<setminus>\<U>`(i #+ 1)" 
    using ZF_fun_from_tot_val2 by simp
  from assms(1,2) have 
    "?\<V>:nat\<rightarrow>Pow(X\<times>X)" "?\<V> {is pairwise disjoint}" and 
    II: "(\<Union>n\<in>nat. \<U>`(n)\<setminus>\<U>`(n #+ 1)) = \<U>`(0)\<setminus>(\<Inter>n\<in>nat. \<U>`(n))"
    using decr_pair_disj1(1,3,4) by simp_all
  from assms(3,4) I have "p\<in>?\<V>`(n)" by simp
  with assms(3) \<open>?\<V>:nat\<rightarrow>Pow(X\<times>X)\<close> \<open>?\<V> {is pairwise disjoint}\<close>
  have "n = \<Union>{i\<in>nat. p\<in>?\<V>`(i)}" using get_the_one by simp
  with assms(3,4) I have "n = \<Union>{i\<in>nat. p\<in>\<U>`(i)\<setminus>\<U>`(i #+ 1)}" and 
    "p \<in> (\<Union>n\<in>nat. \<U>`(n)\<setminus>\<U>`(n #+ 1))"
    by auto
  with II show ?thesis unfolding DistWeight_def by simp
qed

end
