(* 
    This file is a part of IsarMathLib - 
    a library of formalized mathematics written for Isabelle/Isar.

    Copyright (C) 2026 Slawomir Kolodynski

    This program is free software; Redistribution and use in source and binary forms, 
    with or without modification, are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimer in the documentation and/or 
   other materials provided with the distribution.
   3. The name of the author may not be used to endorse or promote products 
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. *)

section \<open>Metrization of uniform spaces\<close>

theory MetricUniform_ZF_1 imports MetricUniform_ZF Real_ZF_2

begin

text\<open>This theory continues \<open>MetricUniform_ZF\<close> specializing to the 
  real valued pseudometrics. The ultimate goal is to show that every uniformity 
  is the supremum of a collection of uniformities generated by a pseudometric. In this
  theory we show the AC-free fragments of the proof of this fact.\<close>

subsection\<open>Metrization lemma\<close>

text\<open>The metrization theorem states that a uniform space is pseudometrizable if and only if 
  its uniformity has an countable base. In this sectiopn we show the key lemma that leads to 
  the metrization theorem.

  In the literature the metrization lemma (proven below) is usually stated as asserting
  existence of a pseudometric satisfying certain conditions. We prefer here a more explicit
  approach where we specify the construction of that pseudometric as a series of definitions,
  then show that the resulting function indeed satisfies the required conditions.
  The drawback of this approach is that we have to come up with names for the intermediate objects
  representing stages of that construction. Naming is hard, so as usual if the reader has an idea
  for better names please let me know. \<close>

text\<open>We define the \<open>DistWeight(\<U>,p)\<close> expression as equal to (real) $0$ if 
  $p\in\bigcap_{n\in\mathbb{N}} \mathcal{U}_n$ or otherwise equal to $(\frac{1}{2})^n$, where
  $n$ is the only natural number such that $p\in\mathcal{U}_n\setminus\mathcal{U}_{n+1}$.
  To understand the context in which this definition is intended to be used suppose 
  $\mathcal{U}:\mathbb{N}\rightarrow \<P>(X\times X)$ is a sequence of subsets 
  of $X\times X$ such that $\mathcal{U}_{n+1}\subseteq \mathcal{U}_n$ for $n\in\mathbb{N}$. 
  Then we have the identity 
  $\bigcup_{n\in mathbb{N}} (\mathcal{U}_n\setminus\mathcal{U}_{n+1})=\mathcal{U}_0\setminus \bigcap_{n\in mathbb{N}} \mathcal{U}_n$ 
  and for any $p\in\bigcup_{n\in mathbb{N}} (\mathcal{U}_n\setminus \mathcal{U}_{n+1})$ 
  there is exactly one $n\in mathbb{N}$ such that $p\in \mathcal{U}_n\setminus \mathcal{U}_{n+1}$
  This means that the set $\{n\in n\in mathbb{N}: p\in \mathcal{U}_n\setminus \mathcal{U}_{n+1}\}$ 
  is a singleton and we can use the $\bigcup \{ x\} = x$ identity to extract its only element.\<close>

definition (in reals) 
  "DistWeight(\<U>,p) \<equiv> if p \<in> (\<Inter>n\<in>nat. \<U>`(n)) then \<zero> else pow(\<Union>{n\<in>nat. p\<in>(\<U>`(n)\<setminus>\<U>`(n #+ 1))},\<onehalf>)"

text\<open>Suppose $\mathcal{U}:\mathbb{N}\rightarrow \<P>(X\times X)$ is a sequence of subsets 
  of $X\times X$ such that $\mathcal{U}_{n+1}\subseteq \mathcal{U}_n$ 
  for all $n\in\mathbb{N}$.
  Assume further that $p\in\mathcal{U}_n\setminus \mathcal{U}_{n+1}$ for some $n\in\mathbb{N}$.
  Then \<open>DistWeight(\<U>,p)\<close> is equal to $\left(frac{1}{2}\right)^n$.\<close>

lemma (in reals) dist_weight_val: 
  assumes "\<U>:nat\<rightarrow>Pow(X\<times>X)" "\<forall>i\<in>nat. \<U>`(i #+ 1) \<subseteq> \<U>`(i)" and
    "n\<in>nat" "p \<in> (\<U>`(n)\<setminus>\<U>`(n #+ 1))" 
  shows "DistWeight(\<U>,p) = pow(n,\<onehalf>)"
proof -
  let ?\<V> = "{\<langle>i,\<U>`(i)\<setminus>\<U>`(i #+ 1)\<rangle>. i\<in>nat}"
  have I: "\<forall>i\<in>nat. ?\<V>`(i) = \<U>`(i)\<setminus>\<U>`(i #+ 1)" 
    using ZF_fun_from_tot_val2 by simp
  from assms(1,2) have 
    "?\<V>:nat\<rightarrow>Pow(X\<times>X)" "?\<V> {is pairwise disjoint}" and 
    II: "(\<Union>n\<in>nat. \<U>`(n)\<setminus>\<U>`(n #+ 1)) = \<U>`(0)\<setminus>(\<Inter>n\<in>nat. \<U>`(n))"
    using decr_pair_disj1(1,3,4) by simp_all
  from assms(3,4) I have "p\<in>?\<V>`(n)" by simp
  with assms(3) \<open>?\<V>:nat\<rightarrow>Pow(X\<times>X)\<close> \<open>?\<V> {is pairwise disjoint}\<close>
  have "n = \<Union>{i\<in>nat. p\<in>?\<V>`(i)}" using get_the_one by simp
  with assms(3,4) I have "n = \<Union>{i\<in>nat. p\<in>\<U>`(i)\<setminus>\<U>`(i #+ 1)}" and 
    "p \<in> (\<Union>n\<in>nat. \<U>`(n)\<setminus>\<U>`(n #+ 1))"
    by auto
  with II show ?thesis unfolding DistWeight_def by simp
qed

end
