name: Style-Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Style-Check
      run: |
        docker build -f isar2html2.0/Dockerfile -t isar2html .
        docker run isar2html
